### ISSUE TITLE
IE11 Error

### ISSUE THREAD

**Issue by cannap** [Justineo/vue-awesome#10]
Hi, 
In Ie11 i get 
`SCRIPT1002: Syntaxerror`

I have 3 Views as Example:
Home, About  and Contact

When i Include the the Plugin just in Contact the whole Page stops working
```
   import Icon from 'vue-awesome/components/Icon.vue'
    import 'vue-awesome/icons/twitter'
    import 'vue-awesome/icons/facebook'
    import 'vue-awesome/icons/send'
```
I cant find which file or debug **damn ie11** it tells me something will be open.. but nothing happens because everything is crashed
Here a Screen: 
https://gyazo.com/48e01c07daa21a267a2de4d9b58ff023
_text comes from ssr_

Weback Version  "webpack": "^2.1.0-beta.20", i will try to update webpack i give report then **i updated same**
my .babelrc
```
{
  "presets": [
    ["es2015", { "modules": false }],    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false
}
and i use require('babel-polyfill')
```

**Comment by Justineo** [comment]
Are you using `vue-cli` to create your project? Can you reproduce the problem if you follow [the steps from this earlier issue](https://github.com/Justineo/vue-awesome/issues/7#issuecomment-255727000)?

**Comment by Justineo** [comment]
@cannap does the last reply work for you?

**Comment by Justineo** [comment]
Closing for now.
