### ISSUE TITLE
Superpower Icon

### ISSUE THREAD

**Issue by NallT** [Justineo/vue-awesome#101]
I recently upgraded to 3.0. The superpower icon appears not to work. It worked on previous versions.

<icon style="color:red; float: right;" size="mini" :name="superpowers"></icon>

I can change the name and the icon appears. It seams to be only the superpowers icon that has issues.

**Comment by Justineo** [comment]
`v3.0` is based on Font Awesome 5 and icon names might change. You should make sure the icon name exists in Font Awesome 5 yourself.

**Comment by NallT** [comment]
Thanks for the update. The name does exist in Font Awesome 5. And it appears in icons.json.

It is not a major issue I will change to a different icon.

**Comment by Justineo** [comment]
You can try with the name `brands/superpowers`. Font Awesome 5 now has multiple icon sets.

**Comment by NallT** [comment]
I see. Thanks!
