### ISSUE TITLE
<icon name="heart-o"></icon> not showing

### ISSUE THREAD

**Issue by mfissehaye** [Justineo/vue-awesome#102]
`<icon name="heart-o"></icon>` not showing

**Comment by Justineo** [comment]
It's not a valid icon name for Font Awesome 5: https://fontawesome.com/icons?d=gallery&q=heart-o.

You may want to use `vue-awesome@2` which is based on Font Awesome 4.

**Comment by mfissehaye** [comment]
I figured to do this using
<icon name="regular/heart"></icon>

**Comment by mfissehaye** [comment]
@Justineo How about social icons like fa-facebook. It doesn't work.

**Comment by Justineo** [comment]
Please read the README carefully: https://github.com/Justineo/vue-awesome#usage
