### ISSUE TITLE
Is the property name required ?

### ISSUE THREAD

**Issue by LeuisKen** [Justineo/vue-awesome#105]
We can found it's required in props validator.
https://github.com/Justineo/vue-awesome/blob/master/src/components/Icon.vue#L77
But in the `Stacked icons` demo, the parent icon component don't have a `name` property.
![qq20180504-112524](https://user-images.githubusercontent.com/7701575/39611954-eb9eac48-4f8d-11e8-9253-19784f741dc2.png)

**Comment by Justineo** [comment]
Not anymore.
