### ISSUE TITLE
3.0 doesn't work anymore with nuxt.js

### ISSUE THREAD

**Issue by ducngtuan** [Justineo/vue-awesome#106]
I don't know what changes happen when you build 3.0 but it won't work on Nuxt.js anymore, even after doing the necessary setup step from the documentation.
2.5.3 works fine.
3.0 doesn't work, with same setup and configuration.
From the Nuxt.js issue, someone suggests the untranspiled components are missing in 3.0. Can you check it?

Here is the error output:
```
These dependencies were not found:

* vue-awesome/icons/comments-o in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["C://proj//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./components/layouts/default/Hello.vue
...
To install them, you can run: npm install --save vue-awesome/icons/comments-o
```

**Comment by Justineo** [comment]
The version update from 2 to 3 for a reason. V3 is based on Font Awesome 5 and icon names are changed. Do not update the major version unless you fully understand what break changes are introduced into the new version. Please read README for detailed usage for the new version.
