### ISSUE TITLE
Fort Awesome just updated!

### ISSUE THREAD

**Issue by AllanPinheiroDeLima** [Justineo/vue-awesome#108]
Hey guys, thanks for the big help doing this plugin. I use almost every app I develop

So, Fort Awesome just updated their icons pack and I was hoping I could use the ruler icon in my new project, along with other new icons, but when I try to use it, it can't download. 

I didn't enter in the project files, but I assume this is caused by a fixed version of FortAwesome ( wich is safer ) in the plugin

Do you guys have plans about update the package ?

Other question: 
Should I update the dependencies manually for now?

**Comment by imbsky** [comment]
@Justineo Maybe this is fixed in #112

**Comment by Justineo** [comment]
Yes, just update to use `vue-awesome@3.0.1`.
