### ISSUE TITLE
Update to Font Awesome 4.7

### ISSUE THREAD

**Issue by rmtuckerphx** [Justineo/vue-awesome#11]
Want to use a new icon from 4.7 (fa-address-card-o) and it is not available in vue-awesome. Great project by the way!

**Comment by Justineo** [comment]
Font-Awesome is updated to `4.7.0` now and the icon data conversion is now easier with a new automated process.

**Comment by rmtuckerphx** [comment]
This project is awesome and so are you. Thanks for updating so quickly!
