### ISSUE TITLE
svg output not clickable for links

### ISSUE THREAD

**Issue by davutkara** [Justineo/vue-awesome#110]
vue-awesome returns icons as svg, when there is a link, svg is not clickable. 
is there any solution? 
thx.

**Comment by davutkara** [comment]
I made click event for outer div then redirect to page.
It's okay, but It seems to be not good solution :)

`@click="$router.push({ path: route.path })"`

**Comment by Justineo** [comment]
You should just wrap an `<a>` element outside the icon for the correct semantics.
