### ISSUE TITLE
Question: What I have to do to use Pro Icons from fa

### ISSUE THREAD

**Issue by rdeutz** [Justineo/vue-awesome#115]
Can someone point me to the right spot to answer the question: how I can use the pro icons from font awesome with vue-awesome?

Thanks

**Comment by Justineo** [comment]
It's not supported now. And I'm not sure if using pro icons in non-official ways conforms to their term of use.

**Comment by rdeutz** [comment]
Thanks, will look what can be done and report back when I have found a solution.
