### ISSUE TITLE
icon "chart-bar" is not showing

### ISSUE THREAD

**Issue by cristianst** [Justineo/vue-awesome#116]
Following is not working: 

`<icon name="regular/chart-bar"></icon>`

Also without the prefix "regular".  Im importing all the icons with `import 'vue-awesome/icons' `

Is there any way to get it working and maybe to import single icons from the regular and brand collection, since that might be much better in order to reduce the bundle.

Thanks in advance.

PS: This is a FontAwesome 5 Icon : https://fontawesome.com/icons?d=gallery&q=chart-bar

**Comment by cristianst** [comment]
**Solution**: The name of the icon is (for some reason) the other way around. `bar-chart` and not `chart-bar` as it appears the FontAwesome Documentation. And beside of that it was not necessary to prefix the icon name with "regular". You might want to fix that naming-inconsitence or just close this ticket :) 

https://fontawesome.com/icons?d=gallery&q=chart&s=regular

**Comment by Justineo** [comment]
Can you provide a reproduction of the problem? The icon `regular/chart-bar` and `chart-bar` both work as expected on my side.

**Comment by Justineo** [comment]
Close due to lack of further information.
