### ISSUE TITLE
Wrong icon style pulling in :eye

### ISSUE THREAD

**Issue by Cre3z** [Justineo/vue-awesome#119]
Hey guys, 

I am trying to use a font-awesome icon with the name eye. According to your documentation all the solid styles are being pulled like so:

"All icons from solid pack are located in vue-awesome/icons directory and have unprefixed name prop values."

However when I do this, I get the regular and not solid style for the icon. See screenshots attached. This is my code: 

```<icon name="eye"></icon>```

This is what I keep getting:
![screenshot from 2018-07-10 23-28-58](https://user-images.githubusercontent.com/17449709/42538876-7cdd3842-8499-11e8-9b63-37fe538b6edf.png)

This is what the solid style looks like:
![screenshot from 2018-07-10 23-29-14](https://user-images.githubusercontent.com/17449709/42538877-7d12e046-8499-11e8-8722-46ed1d710738.png)

TIA

**Comment by Justineo** [comment]
I've now updated to the latest version of FontAwesome, welcome to report back if the problem still exists.
