### ISSUE TITLE
README out of date?

### ISSUE THREAD

**Issue by radicaled** [Justineo/vue-awesome#12]
The README.md says to use this format when using webpack / vue-loader:

```javascript
import Icon from 'vue-awesome/components/Icon.vue'
```

However, there's a parsing error when this happens: `Uncaught SyntaxError: Unexpected token export`. It's caused by this line: https://github.com/Justineo/vue-awesome/blob/757a521af3c609ad17658ccada361e28cf1b799b/src/util.js#L34

This seems to be the correct way of importing the `Icon` component:

```javascript
import Icon from 'vue-awesome'
```

Not sure if the README.md is out of sync.

**Comment by Justineo** [comment]
Importing `vue-awesome` directly will load all icons into your project. Maybe you can check this ul first: https://github.com/Justineo/vue-awesome/issues/7#issuecomment-255727000.

**Comment by Justineo** [comment]
@radicaled have you solved the problem yet?

**Comment by radicaled** [comment]
@Justineo Nope, still using `import Icon from 'vue-awesome'`.

**Comment by Justineo** [comment]
Did you try the solutions I mentioned earlier?

**Comment by radicaled** [comment]
@Justineo Yeah, no effect. Not sure what the problem is, honestly.

**Comment by Justineo** [comment]
It seems that your code in `node_modules` is excluded from those are passed into `babel`. Importing from `vue-awesome` means the whole transpiled ES5 package (which includes all icons and doesn't need further transpiling) is included in your project.

**Comment by radicaled** [comment]
Hm, thanks. I'll fix this problem.

On Mon, Dec 19, 2016, 2:51 AM GU Yiling <notifications@github.com> wrote:

It seems that your code in node_modules is excluded from those are passed
into babel. Importing from vue-awesome means the whole transpiled ES5
package (which includes all icons and doesn't need further transpiling) is
included in your project.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Justineo/vue-awesome/issues/12#issuecomment-267902110>,
or mute the thread

**Comment by Justineo** [comment]
Closing for now. Feel free to reopen if you still have problems.
