### ISSUE TITLE
Importing the souce version on vue-cli@3

### ISSUE THREAD

**Issue by wmzy** [Justineo/vue-awesome#121]
Hi,
I found another way to import the souce version:
```js
// vue.config.js
module.exports = {
  transpileDependencies: [
    // can be string or regex
    'vue-awesome'
  ],
  // ......
};
```

see more: https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel#configuration

**Comment by Justineo** [comment]
Yes you are right. We may add this to README later.

**Comment by Justineo** [comment]
See https://github.com/Justineo/vue-awesome#importing-the-souce-version.
