### ISSUE TITLE
Icons incomplete

### ISSUE THREAD

**Issue by jofftiquez** [Justineo/vue-awesome#125]
I tried to import `vue-awesome/icons/facebook` but it's not existing.

**Comment by Justineo** [comment]
Use 'brands/facebook' instead.

**Comment by jofftiquez** [comment]
I'm getting this error: 
> [Vue warn]: Invalid prop: custom validator check failed for prop "name".

`<fa-icon name="facebook">`

```
import 'vue-awesome/icons/headset';
import 'vue-awesome/icons/brands/facebook';
import Icon from 'vue-awesome/components/Icon';

Vue.component('fa-icon', Icon);
```

**Comment by jofftiquez** [comment]
Nevermind.  I read your component. I should use `<fa-icon name="brands/facebook">`

**Comment by Justineo** [comment]
Yes. From FontAwesome 5+ they provide multiple icon packs so we have to keep this structure.

**Comment by jofftiquez** [comment]
@Justineo Great! Thanks.
