### ISSUE TITLE
3.1.1 Width and Height lost from refactor

### ISSUE THREAD

**Issue by kalvenschraut** [Justineo/vue-awesome#127]
With the latest version the width and height from the registered icons are not being saved in the icons array. 

Looks like the refactor is missing the width and height on the object destructoring  here https://github.com/Justineo/vue-awesome/blob/master/src/components/Icon.vue#L179 and then have to add it to the Object being saved to the icons array. Not sure if defaults want to be set for those, or if width and height is a required property when registering a new SVG icon otherwise I could have done a pull request.

**Comment by Justineo** [comment]
Thanks for reporting! Should be fixed in `v3.1.2`.
