### ISSUE TITLE
(unknown) [Vue warn]: Error when rendering component <icon>: warn (unknown) ReferenceError: _h is not defined

### ISSUE THREAD

**Issue by SidFeng** [Justineo/vue-awesome#13]
anyone can help me ?

**Comment by SidFeng** [comment]
I fix it by myself.it is about npm packages versions

"vue": "2.1.3",
"vue-template-compiler":"2.1.3",
"vue-loader": "10.0.0",

after install this version,it is working now

sudo rm -rf node_modules
sudo npm cache clean
sudo npm install

**Comment by ChrisTerBeke** [comment]
Kept having this issue, no matter which versions I installed. When using WebPack you're better of using https://github.com/gowravshekar/font-awesome-webpack. Works out of the box with

index.js:
``` js
import 'font-awesome-webpack'
```

App.vue:
``` vue
<template>
  <i class="fa fa-thumbs-down"></i>
</template>
```

**Comment by Justineo** [comment]
@ChrisTerBeke have you checked on #7 yet?
