### ISSUE TITLE
How to import icons with names that contain hyphens?

### ISSUE THREAD

**Issue by themathmagician** [Justineo/vue-awesome#131]
Hi there
Thanks for an awesome package.
I try only to import the icons we are actually using, but how do you do that if the name contains hyphens?
`import {
  ellipsis-v
} from 'vue-awesome/icons'`
... the above doesn't work, and I couldnt find an example in the docs / demo / tutorial.
Best
Agata

**Comment by Justineo** [comment]
Currently icon modules are side-effects-only:

```js
import from 'vue-awesome/icons/ellipsis-v'
```
