### ISSUE TITLE
babel 7 problems

### ISSUE THREAD

**Issue by OperKH** [Justineo/vue-awesome#132]
I switched to babel@7 and babel-loader@8 and after that when I run a build I got error:
```Unexpected token: name (icons) [node_modules/vue-awesome/components/Icon.vue:61,0]```

**Comment by Justineo** [comment]
How are you configuring babel-loader?

**Comment by OperKH** [comment]
1. Everesing was configured as in README.md (Vue CLI 2 with the webpack template) - Babel 6
2. After I migrated to Babel 7 I got arrrer as I described.
3. I resolve my issue by removing `.babelrc` and creating `babel.config.js` with that config:
```module.exports = function(api) {
  api.cache(true);
  return {
    presets: [
      [
        "@babel/preset-env",
        {
          modules: false
        }
      ]
    ],
    plugins: ["@babel/plugin-transform-runtime", "transform-vue-jsx"],
    env: {
      test: {
        presets: ["@babel/preset-env"],
        plugins: ["istanbul"]
      }
    }
  };
};
```

Now evrethink OK.
