### ISSUE TITLE
Jest tests fail in 'vue-awesome' import.

### ISSUE THREAD

**Issue by Zicrael** [Justineo/vue-awesome#139]
After run jest unit tests to compomnent with vue-awesome icons tests fail with next error:
 [Error screenshoot](http://prntscr.com/m02cbr)
I trying find solution about 2 days and still stuck on it. 

***.babelrc :***
```
{
  "presets": [
    ["env", {
      "modules": false
    }],
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime", "syntax-dynamic-import"],
  "env": {
    "test": {
      "presets": [
        [
            "env",
            {
                "modules": "commonjs",
                "useBuiltIns": "usage",
                "debug": false
            }
        ],
        "stage-2",
        "jest"
    ],
      "plugins": [
        "transform-vue-jsx",
        "transform-es2015-modules-commonjs",
        "syntax-dynamic-import"
      ]
    }
  }
} 
```
***jest.config.js:***
``` 
module.exports = {
    verbose: true,
    cache: false,
    moduleFileExtensions: [
      "js",
      "json",
      "vue"
    ],
    setupFiles: ["<rootDir>/test/setupTest.js", "jest-canvas-mock"],
    transform: {
      ".*\\.(vue)$": "vue-jest",
      "^.+\\.js$": "babel-jest",
      "^.+\\.jsx$": "babel-jest",
      ".+\\.(css|styl|less|sass|scss|png|jpg|svg|ttf|woff|woff2)$": "jest-transform-stub"
    },
    moduleDirectories: ["node_modules", "bower_components", "shared"],
    moduleNameMapper: {
      "^@/(.*)$": "<rootDir>/src/$1",
      "\\.(css|less|sass|scss)$": "<rootDir>/test/mock/styleMock.js",
    },
    collectCoverage: true,
    collectCoverageFrom: [
      "**/*.{js,vue}",
      "!**/node_modules/**"
    ],
    transformIgnorePatterns: [
      "node_modules/",
      "node_modules/(?!(babel-jest|jest-vue-preprocessor)/)",
      "node_modules/(?!(bootstrap-vue)/)",
      "node_modules(?![\\\\/]vue-awesome[\\\\/])/"
    ],
    coverageReporters: [
      "html",
      "text-summary"
    ]
}
```

Anyone face with same problem in unit testing?

**Comment by Zicrael** [comment]
@Justineo Strange... i try same code, but it is return me same error. In simple components ( like pure vue, no node modules related ) all work fine and all tests pass. Any idea how to fix it?

**Comment by Justineo** [comment]
`.babelrc`:

```json
{
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [
        "veui",
        "transform-vue-jsx",
        [
          "transform-runtime",
          {
            "polyfill": false,
            "regenerator": false
          }
        ]
      ]
    },
    "production": {
      "presets": ["veui"]
    },
    "development": {
      "presets": ["veui"]
    }
  }
}
```

**Comment by Zicrael** [comment]
"veui" required? I refactor config like in you project but widthout "veui" and still same error.

**Comment by Zicrael** [comment]
Maybe problem in webpack config? You add vue-awesome to exclude?

**Comment by Justineo** [comment]
> "veui" required?

No, it's used in another project.

As I understand Jest tests don't go through webpack...

**Comment by Zicrael** [comment]
> Maybe problem in webpack config? You add vue-awesome to exclude?

@Justineo So problem inside webpack?

**Comment by Justineo** [comment]
> So problem inside webpack config?

I don't think so...

Have you tried cleaning up Jest's cache?

```
npx jest --clearCache
```

**Comment by Zicrael** [comment]
@Justineo Yes, also i run test with --no-cahce. I trying fix this strange but about 2 days, and trying anything... Can`t understand why this happend.

**Comment by Justineo** [comment]
Can you create a repo with your current setup so which I may have a look at later?

**Comment by Zicrael** [comment]
Well, its large product wich contain a lot of things. I can try create repo with same issue.

**Comment by Justineo** [comment]
I believe it's only related to Babel and Jest.

**Comment by Zicrael** [comment]
Well, i think to create this project was used vue-cli v2 or >, not v3:( So maybe problem inside.

**Comment by Zicrael** [comment]
In test repo with some compoenents and testing jest + vue-awesome all work fine. So problem inside components  in my app?

**Comment by Zicrael** [comment]
I think i find root of problems! 
Test crash after i make 
``` import { EventBus } from "../../main"; ``` 
in new test component. vue-awesome do  nothing here, its work fine. @Justineo Sorry for bad issue. Need remove that event busses.... Or make new file for it.
