### ISSUE TITLE
How to a add icon color?

### ISSUE THREAD

**Issue by rabichawila** [Justineo/vue-awesome#141]
I'm trying to add color to my icons, and it is not working, i tried to do it this way:

1.  `<icon name="home" scale="2" color="red"></icon>`

2.  `<icon name="home" scale="2" style="color:red"></icon>`
 
3.
```
<div style="color: red">
       <icon name="home" scale="2"></icon>
</div>
```

but none of them, how should i do it?..

**Comment by Justineo** [comment]
Both 2 and 3 should work. Do you have a reproduction?

**Comment by rabichawila** [comment]
> Both 2 and 3 should work. Do you have a reproduction?

I'm still a newbie, what's the reporoduction?..
i've installed it with npm, don't know much..

**Comment by rabichawila** [comment]
@Justineo @johnlindquist @scyclops @Christilut 
Please guys i need your help here..
just getting started with vuejs, i don't know much,

thanks in advance..

**Comment by Justineo** [comment]
@rabichawila Just set the CSS `color` property and it should work. There's not much more I can help...

**Comment by rabichawila** [comment]
Finally fixed the damn thing.

`<icon name="home" style="fill: red;"></icon>`
