### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by rcosta-gcare** [Justineo/vue-awesome#142]
It's a very nice library thank you for the wonderful work.

It seems releases aren't being update anymore, it's very nice to know what changes from version to version.
https://github.com/Justineo/vue-awesome/releases

**Comment by Justineo** [comment]
Changelog is currently managed here: https://github.com/Justineo/vue-awesome/blob/master/CHANGELOG.md

**Comment by rcosta-gcare** [comment]
OK!
Thank you!
