### ISSUE TITLE
Can't set title 

### ISSUE THREAD

**Issue by LiuduZero** [Justineo/vue-awesome#144]
Can't set title on Icon or SVG as usually as other elements

Because i hope move my mouse on Icon , it can show the title such as other elements

**Comment by Justineo** [comment]
As a workaround, you can use this for now:

```html
<v-icon>
  <title>Hoho</title>
  <v-icon name="flag" title="A flag"/>
</v-icon>
```

I'll add `title` as a prop later.

**Comment by LiuduZero** [comment]
node_modules -> vue-awesome -> Icon.vue  ![image](https://user-images.githubusercontent.com/24452177/54730478-281a5b80-4bc4-11e9-9793-e4f9fd89a9d0.png)

> use

![image](https://user-images.githubusercontent.com/24452177/54730493-3bc5c200-4bc4-11e9-8ccb-bcabbe6c7b4e.png)


I tryed it work well, so is this done?

**Comment by LiuduZero** [comment]
> node_modules -> vue-awesome -> Icon.vue ![image](https://user-images.githubusercontent.com/24452177/54730478-281a5b80-4bc4-11e9-9793-e4f9fd89a9d0.png)
> 
> > use
> 
> ![image](https://user-images.githubusercontent.com/24452177/54730493-3bc5c200-4bc4-11e9-8ccb-bcabbe6c7b4e.png)
> 
> I tryed it work well, so is this done?

**Comment by LiuduZero** [comment]
> As a workaround, you can use this for now:
> 
> ```
> <v-icon>
>   <title>Hoho</title>
>   <v-icon name="flag" title="A flag"/>
> </v-icon>
> ```
> 
> I'll add `title` as a prop later.

node_modules -> vue-awesome -> Icon.vue  
![image](https://user-images.githubusercontent.com/24452177/54730570-a37c0d00-4bc4-11e9-83ca-5e4878d723ad.png)


use
![image](https://user-images.githubusercontent.com/24452177/54730577-aaa31b00-4bc4-11e9-9480-519bb497b53e.png)

I tryed it work well, so is this done?

**Comment by LiuduZero** [comment]
Thank you so much , but in my project now, i decide use my way instead of update the version
