### ISSUE TITLE
aria-labelled misspelled

### ISSUE THREAD

**Issue by tvld** [Justineo/vue-awesome#148]
Spelling mistake that Google Lighthouse does not like, correct is ``aria-labeled-by``. Please see:
```js
   let titleId = `vat-${this.id}`
   if (this.title) {
     options.attrs['aria-labelled-by'] = titleId
   }
```
https://github.com/Justineo/vue-awesome/blob/master/src/components/Icon.vue#L206-L208

**Comment by Justineo** [comment]
Fixed in #147
