### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by noikiy** [Justineo/vue-awesome#15]
![54c5a63d-704e-4ffa-a8ff-407e800269c1](https://cloud.githubusercontent.com/assets/977243/21601084/9d4f48b4-d1c0-11e6-972b-8651e12ede65.png)

**Comment by Justineo** [comment]
Could you please provide more information about this issue? Like have you tried the sollutions I provided in earlier issues?

**Comment by lasalvavida** [comment]
Ah, I got it. The babel loader from vue-cli explictly sets include to be 
```javascript
include: [
  path.join(projectRoot, 'src')
]```
You do need to change the exclude value, but you also need to remove this include otherwise they never get looked at in the first place.

**Comment by Youzhigang** [comment]
Create project by using vue-cli, you must to change the /build/webpack.base.conf.js,the loaders at line `40-50.`
```
{
        test: /\.js$/,
        loader: 'babel',
        include: [
          path.join(projectRoot, 'src'),
          path.join(projectRoot,'node_modules/vue-awesome')//add
        ],
        // exclude: /node_modules/
        exclude:/node_modules(?![\\/]vue-awesome[\\/])/
      },
```

**Comment by Justineo** [comment]
Hi guys, I've added the [solution](https://github.com/Justineo/vue-awesome/issues/16) into the readme file. So I'm closing this issue.
