### ISSUE TITLE
Regular icons not working

### ISSUE THREAD

**Issue by focussing** [Justineo/vue-awesome#150]
Wherever I put 'regular' in the import path(s) and/or the icon name; errors appear.
```
<v-icon name="phone"/>
....
<script>
import 'vue-awesome/icons';
import Icon from 'vue-awesome/components/Icon';

export default {
	name: 'footerbar',
	components: {
		'v-icon': Icon
	}
};
</script>
```
Could you provide a working example of how to deal with regular and brands icons?

**Comment by Justineo** [comment]
From [README](https://github.com/Justineo/vue-awesome#usage):

> Icons from `regular` and `brands` are located in `vue-awesome/icons/regular` and `vue-awesome/icons/brands`, which have prefixed `name` prop values like `regular/flag` or `brands/reddit`.

Import on demand:

```js
import 'vue-awesome/icons/brands/reddit'
```

Or import all icons:

```js
import 'vue-awesome/icons'
```

Use in templates:

```html
<v-icon name="brands/reddit"/>
```

**Comment by focussing** [comment]
Don't close this when it is not solved!

`<v-icon name="regular/home"/>`

Invalid prop: prop "name" is referring to an unregistered icon "regular/home".
Please make sure you have imported this icon before using it.
validator @ webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/vue-awesome/components/Icon.vue?vue&type=script&lang=js&:11
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Invalid prop: custom validator check failed for prop "name".

found in

---> <FaIcon> at node_modules/vue-awesome/components/Icon.vue
       <Footerbar>
         <App> at src/App.vue
           <Root>
warn @ webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Error in render: "TypeError: Cannot read property 'paths' of undefined"

found in

---> <FaIcon> at node_modules/vue-awesome/components/Icon.vue
       <Footerbar>
         <App> at src/App.vue
           <Root>
warn @ webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1887 TypeError: Cannot read property 'paths' of undefined
    at Proxy.render (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/vue-awesome/components/Icon.vue?vue&type=script&lang=js&:241)
    at VueComponent.Vue._render (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3536)
    at VueComponent.updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4054)
    at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4467)
    at Watcher.run (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4542)
    at flushSchedulerQueue (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4298)
    at Array.eval (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1979)
    at flushCallbacks (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1905)
logError @ webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1887

**Comment by Justineo** [comment]
How are you importing the icons?

**Comment by focussing** [comment]
as described above
```
<script>
import 'vue-awesome/icons';
import Icon from 'vue-awesome/components/Icon';

export default {
	name: 'footerbar',
	components: {
		'v-icon': Icon
	}
};
</script>
```

**Comment by Justineo** [comment]
`regular/home` is PRO-only. Haven't figured out how to support PRO icons yet.

**Comment by focussing** [comment]
Ehm, how do you generate the FREE icon files at this moment? :)

**Comment by focussing** [comment]
I mean, if you would had the PRO icon files would that help?

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-awesome/blob/master/build/fa2svg.js
https://github.com/Justineo/vue-awesome/blob/master/build/fa2json.js

I am converting the webfont version into SVG first, then to JS modules ATM. A think you can't send me PRO icon files because that might violate the license.

**Comment by focussing** [comment]
Yes you are true about that. Absolutely.

For my personal use I could try to make a kind of icon pack with the two js files you provide?
Could you explain how to do that?
Thank you very much.

**Comment by Justineo** [comment]
You need to make some modifications to those scripts, of course.

The free icons are located here so you probably want to change this:

https://github.com/Justineo/vue-awesome/blob/master/build/fa2svg.js#L26

And other stuff are determined by how PRO icons are structured, so you have to look into that yourself.
