### ISSUE TITLE
V-bind for name of icon issue

### ISSUE THREAD

**Issue by AnhNguyen-Lewis** [Justineo/vue-awesome#151]
This is my code, I try to dynamically assign the name of icon

`<p> {{props.row.category}} <v-icon class = "icon" :name="categoryIcon(props.row.category)"/> </p> `

and my function
`categoryIcon (category) {
            console.log("hello")
            if (category == 'Leadership'){
                return "users"
            }
            else if (category == 'Project'){
            return "project-diagram"
            }
            else return "question"
        }`

I am new to Vue but I really want to assign dynamically the name of icon
Any help is appreciated

**Comment by Justineo** [comment]
Not sure what your problem is. The only thing I can suggest is to make sure the icon name you are using refer to something exists in free icon packs and use a pack prefix if you are using the `regular` or `brand` icon pack.

**Comment by AnhNguyen-Lewis** [comment]
@Justineo I want to dynamically assign the name of the icon by the category
if the category is "project" i want it to show the Project-diagram icon
please help me

**Comment by Justineo** [comment]
I've already helped you as much as I can. If you did what I suggested and it still doesn't work I'm afraid your problem isn't actually related to this project.
