### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by asxcandrew** [Justineo/vue-awesome#16]
app.js 

```
import Vue from 'vue'
import BootstrapVue from 'bootstrap-vue';
import Icon from 'vue-awesome/components/Icon.vue'

import  { event } from './utils'
import store from './store'

Vue.use(BootstrapVue);
Vue.component('icon', Icon);

const app = new Vue({
  el: '#app',
  store,
  render: h => h(require('./main.vue')),
  created () {
    event.init()
  }
})

export { app, store }
```
"brunch": "2.7.4"
"vue": "2.1.8"

![screenshot from 2017-01-04 07-18-38](https://cloud.githubusercontent.com/assets/1057914/21632355/3d3406e8-d24e-11e6-8dce-f894347f570e.png)

Has anyone encountered this problem?

**Comment by Justineo** [comment]
It looks like that there's something wrong with your Webpack config. Are you using `vue-loader` correctly?

**Comment by asxcandrew** [comment]
I use brunch. How to use vue-awersome with brunch?

**Comment by Justineo** [comment]
I haven't used brunch so I'm not sure about the issue here right now.

**Comment by antonioreyna** [comment]
im getting this: 

```
dist/app.0dc74645fc9cf0f68122.js from UglifyJs
SyntaxError: Unexpected token: name (warn) [./~/vue-awesome/util.js:3,0][dist/app.0dc74645fc9cf0f68122.js:607,4]
```

**Comment by HADB** [comment]
same as @antonioreyna, util.js is incompatible with uglifyjs.

**Comment by Justineo** [comment]
@antonioreyna @HADB 

Have you tried [the solution in the readme](https://github.com/Justineo/vue-awesome#heads-up) yet?

**Comment by HADB** [comment]
@Justineo This works for me:

```
exclude: /node_modules(?![\\/][\S]*vue-awesome[\\/])/
```

The real path for `vue-awesome` in `node_modules` is `.2.1.0@vue-awesome` not `vue-awesome`

BTW, is the file "util.js" necessary?

**Comment by antonioreyna** [comment]
i got it working yes with the exclude thing

**Comment by HADB** [comment]
I know why mine's different. I used cnpm instead of npm to install the packages beacuse of the network problem in China. There's a little difference between cnpm and npm.

**Comment by JiriChara** [comment]
I think instead of doing: `npm run icons && npm run build && cp -r ./src/* . && rm index.js` when pre-publishing, you need something like: `npm run icons && npm run build && cross-env BABEL_ENV=commonjs babel src --out-dir . && rm index.js`. I can't test it locally, because of `cnpm`...

**Comment by JiriChara** [comment]
yeah actually it seems to work. I am getting proper es5 compatible util.js now:

```js
// Copied from vue/src/core/util/debug.js

var warn = function warn() {};

if (process.env.NODE_ENV !== 'production') {
  var hasConsole = typeof console !== 'undefined';

  warn = function warn(msg, vm) {
    if (hasConsole) {
      console.error('[Vue warn]: ' + msg + ' ' + (vm ? formatLocation(formatComponentName(vm)) : ''));
    }
  };

  var formatComponentName = function formatComponentName(vm) {
    if (vm.$root === vm) {
      return 'root instance';
    }
    var name = vm._isVue ? vm.$options.name || vm.$options._componentTag : vm.name;
    return name ? 'component <' + name + '>' : 'anonymous component';
  };

  var formatLocation = function formatLocation(str) {
    if (str === 'anonymous component') {
      str += ' - use the "name" option for better debugging messages.';
    }
    return '(found in ' + str + ')';
  };
}

export { warn };
```

**Comment by Justineo** [comment]
Webpack config no longer need to be modified since `v2.2.5` because warnings are utilizing `Vue.util.warn` now.
