### ISSUE TITLE
Error: strict-type-predicates: Expression is always false. with Typescript in strict mode.

### ISSUE THREAD

**Issue by RagazziMoscow** [Justineo/vue-awesome#169]
I have import `Icon` component in `ts` file(not in template) when i register my `v-icon`.

```
import Icon from 'vue-awesome/components/Icon.vue'

import 'vue-awesome/icons/university'
import 'vue-awesome/icons/chart-pie'
/* other icons */

Vue.component('v-icon', Icon)
```

In my `tsconfig.json` i have set `"strict": true` option.
So i got an error during the compilation:
```
client/node_modules/vue-awesome/components/Icon.vue(184,9):
strict-type-predicates: Expression is always false.
```
Setting `"node_modules/vue-awesome/components/Icon.vue"` into the `exclude` section in `tsconfig.json` doesn't help me.

Do you have any ideas for workaround ?

**Comment by RagazziMoscow** [comment]
This problem is because of `tslint` checking. So i solved it by excluding all the files inside my `node_modules`. To exclude them i added to `tslint.json` path:

```
{
  /* ... */
  "linterOptions": {
    "exclude": [
      "node_modules/**/*.*"
    ]
  },
  /* ... */
}
```
It works.
This issue can be closed.

**Comment by Justineo** [comment]
Thanks for sharing this :)
