### ISSUE TITLE
Color prop is not being respected

### ISSUE THREAD

**Issue by RyanPayso13** [Justineo/vue-awesome#173]
I am having an issue converting my icons to white color.

The following code is working fine in dev server but not in production where I deploy to Netlify.

The code is as follows:

```
    <div class="flex justify-center mt-8">
      <a class="mr-4" href="https://github.com/RyanPayso13">
        <v-icon color="white" name="brands/github" scale="6" />
      </a>
      <a href="https://www.facebook.com/ryan.pays">
        <v-icon color="white" name="brands/facebook" scale="6" />
      </a>
      <a class="ml-4" href="/doc/ryan-pays-cv.pdf" target="_blank">
        <v-icon color="white" name="file-pdf" scale="6" />
      </a>
    </div>
```
And the code deployed to production is here:

[http://www.ryanpays.com](http://www.ryanpays.com)

Can you please help me as to what is wrong?

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-awesome#colors
