### ISSUE TITLE
SyntaxError: Unexpected token: name (warn) [./~/vue-awesome/util.js:3,0]

### ISSUE THREAD

**Issue by antonioreyna** [Justineo/vue-awesome#18]
im using webpack and i get this.

**Comment by Justineo** [comment]
The problem cannot be reproduced with the given information and there have been quite a few discussions regarding transpiling ES Next code. Have you tried those sollutions I provided in ealier issues?

**Comment by antonioreyna** [comment]
hi, i got it working i had to add some webpack config.. and install lot of modules :) 

```
require('laravel-elixir-webpack-official');

Elixir.webpack.mergeConfig({
    module: {
        loaders: [{
            test: /\.js$/,
            loader: 'babel-loader',
            exclude: /node_modules(?![\\/]vue-awesome[\\/])/
        }]
    }
});
```

**Comment by Justineo** [comment]
OK. It's actually listed in readme. Closing this issue.

**Comment by hank2718** [comment]
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-awesome')]
      },
It will still be wrong
