### ISSUE TITLE
Does this project will support vue3?

### ISSUE THREAD

**Issue by PeterlitsZo** [Justineo/vue-awesome#180]
title.

**Comment by NoahCardoza** [comment]
I'm wondering the same thing but it looks dead to me...

**Comment by PeterlitsZo** [comment]
> I'm wondering the same thing but it looks dead to me...

Yes, this project looks not going to maintain... So if you find some project that is accessable by vue3, could you comment it please? I think it is helpful if you could comment. 😄

**Comment by JakeAtTurner** [comment]
Here is a fork with vue3 support

https://github.com/JakeAtTurner/vue-focus/tree/vue3.0-build

**Comment by PeterlitsZo** [comment]
> Here is a fork with vue3 support
> 
> https://github.com/JakeAtTurner/vue-awesome/tree/vue3.0-build

Thanks!
