### ISSUE TITLE
Work with the Nuxt Framework

### ISSUE THREAD

**Issue by CDuane** [Justineo/vue-awesome#19]
Hi, I am trying to make this work with the Nuxt Framework.
I added vue-awesome to nuxt.config.js
`build: {
		vendor: ['vue-awesome']
	}`

When I insert an icon in a template it does not show, but it is there (in the dev tools).

Am I missing something?
Thanks.

**Comment by Justineo** [comment]
You need to import icons you need manually the way listed in the [readme](https://github.com/Justineo/vue-awesome#es-modules-with-npm--vue-loader-recommended). You can import `vue-awesome/icons` directly if you don't care about the bundle size.

**Comment by CDuane** [comment]
Thanks @Justineo I missed that. :)
