### ISSUE TITLE
4.2.0之后的版本将components/Icon.vue编译为components/Icon.js导致按需加载找不到Icon组件

### ISSUE THREAD

**Issue by Sun79** [Justineo/vue-awesome#190]
所有的按需加载图标都是加载的Icon.vue组件，请作者在发布时包含Icon.vue文件或修改图标文件引入组件方式，谢谢。

**Comment by Justineo** [comment]
README 的示例写的是 `vue-awesome/components/Icon`，并没有保证是 `.vue` 文件呀。

**Comment by Sun79** [comment]
[![按需加载](https://z3.ax1x.com/2021/05/18/gWzzUf.png)](https://imgtu.com/i/gWzzUf)
按需加载单独引入图标文件内都是引入的.vue文件库😂

**Comment by Justineo** [comment]
看来这是个 bug 😅
