### ISSUE TITLE
Invalid Prop

### ISSUE THREAD

**Issue by emjimadhu** [Justineo/vue-awesome#24]
`[Vue warn]: Invalid prop: custom validator check failed for prop "name". 
(found in component <icon> at /var/www/html/vueApp/node_modules/vue-awesome/components/Icon.vue)`

i am having this problem. what might be the solution?
i followed everything as in readme..!

**Comment by Justineo** [comment]
Did you `import`ed the specific icons you are using?

**Comment by emjimadhu** [comment]
not the specific icon but global in my `main.js` and this what i placed

`import Icon from 'vue-awesome/components/Icon.vue'
Vue.component('icon', Icon)`

and in my component page i used 

`<icon name="flag"></icon>`

**Comment by Justineo** [comment]
It seems that you are **not** following [the steps in README.md](https://github.com/Justineo/vue-awesome#es-modules-with-npm--vue-loader-recommended).

**Comment by emjimadhu** [comment]
ok im still confused.. im new vue.. its really hard for me to get it work.. i read readme.. but not working, may be i am doing wrong? 

at first in main.js used 
`import Icon from 'vue-awesome/components/Icon.vue' Vue.component('icon', Icon)`

and in my component 
`<icon name="flag"></icon>`

that error came.

next i included locally 
`import Icon from 'vue-awesome/components/Icon.vue'
export default {
  components: {
    Icon
  }
}`

still same error.. can you please point me out? at first where i have to include the file and refrence it?

**Comment by Justineo** [comment]
```js
// only import the icons you use to reduce bundle size
import 'vue-awesome/icons/flag'

// or import all icons if you don't care about bundle size
import 'vue-awesome/icons'
```

**Comment by emjimadhu** [comment]
so i have to import in my main.js file.. thats all? after that i can start using it in my componenets? im really sorry for this newb question.

**Comment by Justineo** [comment]
You can either import single icons or the whole icon package anywhere in your code.

**Comment by emjimadhu** [comment]
thank you it worked..!
