### ISSUE TITLE
Minimize issue

### ISSUE THREAD

**Issue by akubasa** [Justineo/vue-awesome#25]
When I run webpack build with Uglifyjs plugin or --optimize-minimize it gives me following error

ERROR in build.js from UglifyJs
SyntaxError: Unexpected token: name (warn) [./~/vue-awesome/util.js:3,0][build.js:...

When I run the build withput minification or dev Its working great.

I am importing the Icon in my components, I also tried the global import, still not working I tried ES5 and ES6 

I am now importing like:

require('vue-awesome/icons/search');
require('vue-awesome/icons/times');
var Icon = require('vue-awesome/components/Icon.vue');

And then I define in module.exports

        components: {
            'icon': Icon
        },

It is working but only in dev builds, Am I missing something?

**Comment by akubasa** [comment]
As a temporary solution I just removed the utli import in the Icon.vue file and removed the "warn" on line 82 (I am using current version)

**Comment by Justineo** [comment]
That's probably your file is not transpiled into ES5 before you minimize it. Did you follow the instructions in [readme](https://github.com/Justineo/vue-awesome#heads-up)?

**Comment by akubasa** [comment]
Thank you for your fast response.
I think this will be the issue. I will try later today and let you know.

**Comment by akubasa** [comment]
this babel config

    {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules(?![\\/]vue-awesome[\\/])/,
        include: ['src', path.resolve(__dirname), 'node_modules/vue-awesome']
    },
