### ISSUE TITLE
ERROR in static/js/vendor.b8806fb0e903c18740bc.js from UglifyJs SyntaxError: Unexpected token: name (warn) [./~/.2.1.0@vue-awesome/util.js:3,0][static/js/vendor.b8806fb0e903c18740bc.js:89356,4]

### ISSUE THREAD

**Issue by hank2718** [Justineo/vue-awesome#27]

**Comment by sdeprez** [comment]
Duplicate of #18

**Comment by Justineo** [comment]
See #18.

**Comment by hank2718** [comment]
It will still be wrong
  {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-awesome')]
      },

**Comment by hank2718** [comment]
for webpack2

**Comment by Justineo** [comment]
Are you using Windows? If so, you may try use `resolve('node_modules\\vue-awesome')` instead.

**Comment by hank2718** [comment]
using  mac os
