### ISSUE TITLE
Vue 2.0

### ISSUE THREAD

**Issue by sarik93** [Justineo/vue-awesome#3]
In Vue 2.0 can write camelCase attributes, and .camel not working.

**Comment by QWp6t** [comment]
lol u drug?

**Comment by Justineo** [comment]
Vue 2.0 is not released yet so I'll probably fix this later.

**Comment by Justineo** [comment]
@sarik93 Let's keep this open until it works well for 2.0. :)

**Comment by sarik93** [comment]
And props method "coerce" in 'scale' deprecated need transfer to computed fields.

**Comment by beeplin** [comment]
hey guys, vue 2.0 has been officially released for 4 days~

**Comment by flip-santos** [comment]
Hey guys, I'll follow this thread too, I'm using vue 2.0 in my project and I was doing a icon component as well
