### ISSUE TITLE
npm package seems broken?

### ISSUE THREAD

**Issue by kartojal** [Justineo/vue-awesome#30]
Hi,

My pipeline/CI build is failing since your last npm version. When building my nuxt application, Webpack resolver do not finds any font awesome icons with `import "vue-awesome/icons/fa-some-icon"` way. Version 2.2.3 works as expected.

Can add more details later if you want

Workaround for now: Set vue-awesome to 2.2.3 in package.json file.

**Comment by Justineo** [comment]
Oops. Actually those icon names with `fa-` prefix were unintentionally added into the package. You can use those without `fa-` prefix (`fa-flag` → `flag`). It's a breaking change for those projects relying on the prefixed version.

**Comment by kartojal** [comment]
Oh. Good to know, so i will fix the paths. Thanks for the fast response!

**Comment by Justineo** [comment]
Sorry for the trouble. I'll leave this issue open for a while in case others run into the same problem.

**Comment by bdharris08** [comment]
This broke our app too :(
