### ISSUE TITLE
Can not get around vue-awesome

### ISSUE THREAD

**Issue by besnikh** [Justineo/vue-awesome#32]
Hi, 

First, I want to note that I am new to Vue, but I am trying to add font awesome to my project, and last 4 hours I can't get around it!!! 

So, I cloned this code to start my project: [https://github.com/hal0gen/vue-foundation](https://github.com/hal0gen/vue-foundation)

Then I followed your instructions as following: 
1. I've installed vue-awesome via npm 

2. My main JS look like this: 
```
import Icon from 'vue-awesome/components/Icon';
import jQuery from 'jquery';
import Vue from 'vue';
```
and below: 
```
Vue.component('icon', Icon);

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App, Icon },
});
```

3. my webpack.base.conf.js looks like: 
```

        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')],
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-awesome')]
      },

```

Now, if I go to my home.vue and add an Icon, I don't see the Icon in my browser.. what Am I missing ?> 
Can someone please help me with this :(

**Comment by Justineo** [comment]
Did you import icon modules into your code?

```js
import 'vue-awesome/icons/flag' // import separately

// or

import 'vue-awesome/icons' // import all icons together
```

**Comment by besnikh** [comment]
@Justineo :+1: This feels so bad, I just forgot about that. 

Thank you bro, I had a typo and I forgot to import it :) 

Cheers!
