### ISSUE TITLE
dist file includes Vue 2.2.6

### ISSUE THREAD

**Issue by LinusBorg** [Justineo/vue-awesome#33]
See here:

https://github.com/Justineo/vue-awesome/blob/master/dist/vue-awesome.js#L2-L6

That's just unnecessary at best and will create a duplicate Vue instance in the user's application at worst, leading to other Plugins potentially not working correctly etc.

It would be better to define Vue as an [external ](https://webpack.js.org/configuration/externals/#components/sidebar/sidebar.jsx).

**Comment by Justineo** [comment]
It's obviously unwanted. Yes I'll fix it asap.

**Comment by LinusBorg** [comment]
> It's obviously unwanted. 

I thought so. Great component otherwise, keep it up! :)

**Comment by Justineo** [comment]
Latest bundled version should fixed this problem. (Also switched to rollup and the size is now about 50k smaller.)
