### ISSUE TITLE
Icons loose spin, flip and color since vue-awesome v2.2.8

### ISSUE THREAD

**Issue by ChuckFields** [Justineo/vue-awesome#35]
[https://jsfiddle.net/h3exoxhL/7/](https://jsfiddle.net/h3exoxhL/7/)

After updating vue-awesome to v2.2.8 or later, the icons no longer work with respect to spin, flip or color. In my jsfiddle example, if you use vue-awesome v2.2.7 everything works. Otherwise I end up black, non-spinning, non-flipped icons.

**Comment by Justineo** [comment]
For versions after 2.2.8 I switch the bundler to Rollup and missed CSS configuration for that. It's fixed in v2.3.1 now.
