### ISSUE TITLE
Error building icons

### ISSUE THREAD

**Issue by skycult** [Justineo/vue-awesome#39]
Hi,
 if I try to run `nom run fa2json` I see this error:

> node build/fa2json.js

```bash
events.js:161
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'charCodeAt' of undefined
    at /Users/Sky/Documents/vue-awesome/node_modules/svgfont2js/index.js:56:39
```
What's I missing?
Thanks

Best regards

**Comment by Justineo** [comment]
I cannot reproduce the problem. What did you do before you run the script? Are you trying to generate custom icons?

**Comment by Justineo** [comment]
Is there still a problem? I'm closing this now but if you have further issues, please feel free to reopen.

**Comment by dotneet** [comment]
related pr on svgfont2js:
https://github.com/riobard/svgfont2js/pull/3
