### ISSUE TITLE
Vue-awesome module package error by Webpack

### ISSUE THREAD

**Issue by 1657413883** [Justineo/vue-awesome#40]
Unexpected token: name (warn) [./~/vue-awesome/util.js:4,0]

this code :  
let warn = () => {}

**Comment by Justineo** [comment]
Which version are you using? It shouldn't be a problem for the latest version.

**Comment by 1657413883** [comment]
thank for your answer.
The version of vue-awesome is ^2.0.2. 
Packaged in the server, in addition to Google and Firefox other browsers will be due to the error of the package suggested that the syntax error, and not go to the site.
for example: IE.The following code syntax is wrong
let warn = () => {}

**Comment by 1657413883** [comment]
Accurate to say "version": "2.1.0"

**Comment by Justineo** [comment]
Update to latest version should solve the problem.
