### ISSUE TITLE
ES6 imports in vue-awesome modules are breaking in electron-forge

### ISSUE THREAD

**Issue by gimyboya** [Justineo/vue-awesome#41]
I have struggled for a long time trying to integrate `vue-awesome` with `electron-forge` and the problem was the ES6 import syntax in `vue-awesome` modules here i am tagging the [issue](https://github.com/electron-userland/electron-forge-templates/issues/36) please look into it

**Comment by Justineo** [comment]
I know nothing about `electron-forge` so I don't know how to load ES Next modules into it.
If you are using Electron then the bundle size might not be so critical. You can just use the [precompiled version](https://github.com/Justineo/vue-awesome/blob/master/dist/vue-awesome.js), which is a UMD module and you can use it in AMD/CommonJS environments or just drop a `<script>` tag into your HTML file and use the global variable `VueAwesome`.

**Comment by Justineo** [comment]
Just don't know how to help.
