### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by dmitry7887** [Justineo/vue-awesome#43]
Hi, 
I have the issue with importing component for SSR usage.
`ReferenceError: document is not defined
    at /node_modules/vue-awesome/dist/vue-awesome.js:1:315`
Could you please describe how to use font awesome with SSR correctly?

**Comment by Justineo** [comment]
Now Vue-Awesome is built with Rollup.js. It seems this issue is related to vuejs/rollup-plugin-vue/issues/101.

**Comment by Justineo** [comment]
You should not use the precompiled version if you want SSR to work (at least for now).

Import the component like this shall help:
```js
import Icon from 'vue-awesome/components/Icon'

// if you want all icons
import 'vue-awesome/icons'

// if you want to pick only a few icons
import 'vue-awesome/icons/flag'
import 'vue-awesome/icons/star'
```

**Comment by esiao** [comment]
I had the same issue in a Nuxt environment.
I managed to fix it using Nuxt plugins and registering the component render function directly for SSR. Dropping this here as it could be useful for others

In /plugins/icons.js
```
import Vue from 'vue'

let component = {}

if (process.browser) {
  component = require('vue-awesome/components/Icon')

  require('vue-awesome/icons/arrow-left')
  require('vue-awesome/icons/check')
  require('vue-awesome/icons/chevron-right')
}
else {
  component.name = 'icon'
  component.render = function(){var t=this,q=t.$createElement,h=t._self._c||q;return h("svg",{class:t.clazz,style:t.style,attrs:{version:"1.1",role:t.label?"img":"presentation","aria-label":t.label,x:t.x,y:t.y,width:t.width,height:t.height,viewBox:t.box}},[t._t("default",[t.icon&&t.icon.paths?t._l(t.icon.paths,function(q){return h("path",t._b({},"path",q))}):t._e(),t.icon&&t.icon.polygons?t._l(t.icon.polygons,function(q){return h("polygon",t._b({},"polygon",q))}):t._e(),t._v("\b"),t.icon&&t.icon.raw?[h("g",{domProps:{innerHTML:t._s(t.icon.raw)}})]:t._e()])],2)}
}

Vue.component('icon', component)
```

In nuxt.config.js
```
module.exports = {
  ...
  plugins: [
    { src: '~plugins/icons.js' }
  ],
  ...
}
```

**Comment by SteveCruise** [comment]
Thank you @Justineo !!!

**Comment by andersrehn** [comment]
I know that there are some issues with the pre built bundle of `vue-awesome` and that SSR wont work.

Here was my problem and maybe a solution for anyone else out the.
I have a vue SSR app ([based on a structure like this](https://github.com/doabit/vue-ssr-starter-kit)) (not using nuxt.js) and using the snippet.
```
import Icon from 'vue-awesome/components/Icon'

// if you want all icons
import 'vue-awesome/icons'

// if you want to pick only a few icons
import 'vue-awesome/icons/flag'
import 'vue-awesome/icons/star'
```

Will work, however with webpack I had the issue that the output `app-client.js` bundle did not transpile some functions from `vue-awesome`, thus breaking IE11 compatibility.  

My solution was to on the `client-entry.js`-side was:
```
import { createApp } from './app';
import * as Icon from 'vue-awesome'; 
...
```
And when I got to the location of creating a new app I will pass the imported `Icon` to the app as a paramter.

My solution was to on the `server-entry.js`-side was:
```
import { createApp } from './app';
import 'vue-awesome/icons';
import Icon from 'vue-awesome/components/Icon';
```
and from here also pass the Icon as a parameter to my app object.

Inside my `app.js` that holds the `createApp` method.
```
export function createApp (ssrContext, extraComponents) {
    const store = createStore();
    const router = createRouter();
    if (ssrContext) {
        Vue.component('icon', extraComponents.icon);
    } else {
        Vue.component('icon', extraComponents.icon);
    }
.....
}
```
extraComponents is just an object that contains `{ icon: Icon }` but can be extended if more plugins have some SSR compatibility issues.
