### ISSUE TITLE
Rotation Speed (spin)

### ISSUE THREAD

**Issue by TonBits** [Justineo/vue-awesome#47]
It seems that the speed of the rotation when adding the spin attribute is so much faster then the original font-awesome animation speed.

The live demo
https://justineo.github.io/vue-awesome/demo/

Compared to
http://fontawesome.io/examples/

Is there away to adjust the speed here to use the default from font-awesome?

**Comment by Justineo** [comment]
Just add CSS `animation-duration` declarations yourself.

```css
.fa-spin {
  animation-duration: 2s;
}
```

**Comment by TonBits** [comment]
Yes, I figured it out. Adding a scoped style to my page to match the animation speed of the original font-awesome.

I will close this out, but you might want use the same original animation speed as default as well.

Thanks
