### ISSUE TITLE
Is it possible to import icons which you use without registering icons?

### ISSUE THREAD

**Issue by qiangzi7723** [Justineo/vue-awesome#48]
I care about the bundle size so I use `import 'vue-awesome/icons/flag'` instead of `import 'vue-awesome/icons'`.

However, I found I have to register the icon which I use in the demo.

So, I want to know is it possible to import icons auto?

Such as detecting the vue file for searching the icon which I use and inject auto ?

Thank you. 

The vue-awesome is awesome !

**Comment by Justineo** [comment]
This can be done by providing a Webpack loader which scans Vue templates and generates the import statements. But there are two main problems here:

1. The component name is specified by users in `components` of the context component, whose syntax is not static so I cannot make any assumption about this.
2. Users can use icons in render functions and it's impossible to figure out which icons are used.

If the automatic process cannot guarantee all icons can be detected, it doesn't have so much value IMO.

So I'm not gonna implement this feature. Thanks for the suggestion anyway. 👍
