### ISSUE TITLE
Icon inside bootstrap button

### ISSUE THREAD

**Issue by aleksandrmelnyk** [Justineo/vue-awesome#52]
Hi,

am using vue with bootstrap and trying add icon to bs button, but it appeared to be misaligned. 
Id there any solution to this?

`<button class="btn btn-outline-success my-2 my-sm-0" type="submit"><icon name="flag"></icon>Search</button>`

![2017-08-07_1017](https://user-images.githubusercontent.com/930971/29016112-b08fb36c-7b59-11e7-81ac-b4e6616cbf7f.png)

**Comment by f** [comment]
Add a global style:

```
  .btn .fa-icon {
    vertical-align: middle;
    margin-right: 0.5rem;
  }
```

**Comment by aleksandrmelnyk** [comment]
Thanks, that worked
