### ISSUE TITLE
Couldn't find any versions for "vue-awesome" that matches "^2.3.2"

### ISSUE THREAD

**Issue by jonnyparris** [Justineo/vue-awesome#54]
Please can the latest version be published to npm so I can make use of the pulse prop?
I tried installing straight from the git repo but it's causing the following error my unit tests:
`Uncaught Error: Module build failed: Error: Plugin 0 specified in "/home/my_user/my_project/node_modules/vue-awesome/.babelrc.env.test" provided an invalid property of "Instrumenter"`
Fixing at the source would be ideal if possible.

**Comment by Justineo** [comment]
`+ vue-awesome@2.3.2`
