### ISSUE TITLE
How do I load a complex svg with groups

### ISSUE THREAD

**Issue by choskim** [Justineo/vue-awesome#55]
I want to have register elements without manually having to pass strings of paths or polygons. If a have a complex SVG with groups, is there a way to import that file as a value of a key during icon registration. Is the only way to do this with something like this:

```
raw: require('./path/to/svg');
```

**Comment by Justineo** [comment]
If possible, you can convert SVG content to paths only or polygons only and you can use `paths` or `polygons` to register icons. If you cannot work this around, then you can use the `raw` way. (better with SVGO integrated into your workflow)

**Comment by Justineo** [comment]
Closing for now. If you still got problems on this, feel free to reopen.
