### ISSUE TITLE
This dependency was not found:  * vue-awesome in ./src/main.js

### ISSUE THREAD

**Issue by tribhuwank** [Justineo/vue-awesome#56]
I am facing issue about not able to have vue-awesome work for my webpack 2 vue application . I follow the instruction and done my setting according the following:
1>npm install --save vue-awesome
2>then in webpack,base.config.js  
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-awesome')] // include: [resolve('src'), resolve('test')]
      },
3>and import in main.js
import Icon from 'vue-awesome'
Vue.use(Icon)
 

But still not working with error This dependency was not found:  * vue-awesome in ./src/main.js

**Comment by nicho90** [comment]
@tribhuwank I had the same problem and solved it by this:

**main.js**
```js
import Vue from 'vue'

import 'vue-awesome/icons'
import Icon from 'vue-awesome/components/Icon.vue'

Vue.component('icon', Icon)
```

**webpack.config.js**
```
exclude: /node_modules(?![\\/]vue-awesome[\\/])/
```

So instead of using `include`, I added `vue-awesome` to the `exclude`option with a Regex to get passed by webpack. I hope this works for you too!

Cheers, Nicho ✌️

**Comment by Justineo** [comment]
Thank you @nicho90!

Is Nicho's solution up there working for you? @tribhuwank

**Comment by Justineo** [comment]
Closing this as a workaround is already provided.
