### ISSUE TITLE
Allow to use font awesome icons in pseudo classes

### ISSUE THREAD

**Issue by Draluy** [Justineo/vue-awesome#59]
I'm trying to reference an icon like this:

`.telephone:before{
    font-family: FontAwesome;
    content: "\f095";
}`

But this fails as it seems the actual icons are not in the font, but in separate .js files?
Is there a workaround to this?

**Comment by Justineo** [comment]
It's not gonna happen for this project. If you want to use icon font, you can use FontAwesome directly.
