### ISSUE TITLE
Sweetalert case

### ISSUE THREAD

**Issue by saintplay** [Justineo/vue-awesome#61]
Hello, thank you so much for creating this component!

I'm having **trouble** with this particular scenario:

I'm using the **Icon** component in almost every component I created,
except in this file

![image](https://user-images.githubusercontent.com/9372893/30605843-48d7c1a8-9d35-11e7-9ee4-b7bad45b16f2.png)

It seems, I need to use the `fa fa-bug` legacy class;

I don't want to include the font awesome library just for this,

There is something I can do to solve my problem?

Thanks in advance

**Comment by Justineo** [comment]
I've worked out a solution here:

https://jsfiddle.net/Justineo/0h3tsgby/

You have to make Vue dynamically compile a template including icon components (or other components)  and mount them inside SweetAlert's boxes upon open (and destroy those temporary components before close).

**Comment by saintplay** [comment]
Vue compile is how you do it!
Thanks so much

**Comment by saintplay** [comment]
I think you can also render the icons at build time:

*somewhere, globally accessible in your application*
```html
<div style="display:none">
  <div id="bug-icon-rendered">
  </div>
</div>
```

**Comment by Justineo** [comment]
That's a bad practice IMO. Dynamically compile dialog content might not be the solution with best performance but it's more natural and it'll help keep the content reactive.

**Comment by saintplay** [comment]
Yes, I agree but I think it is the best solution for my app architecture,  I like the solution you write in the jsfidle though, I learn something new today :)
