### ISSUE TITLE
vue-Awesome and Bootstrap

### ISSUE THREAD

**Issue by alexiej** [Justineo/vue-awesome#63]
Hi,

I found that vue-awesome doesn't look good with the bootstrap button. Is it possible to fix this?
As you can see it is little upper than "fa" icon and not centered.

 ```
  <button class="btn btn-outline-success">
                <icon name="chevron-left"  inverse="true" ></icon>
               <i class="fa fa-chevron-left" aria-hidden="true"></i>
   </button>
```
 
![image](https://user-images.githubusercontent.com/12593751/30950719-facc7580-a41e-11e7-9f78-a4150e1c97b9.png)

```
<button class="btn btn-outline-success">
          <icon name="chevron-left"  inverse="true" ></icon>
</button>

 <button class="btn btn-outline-success">
         <i class="fa fa-chevron-left" aria-hidden="true"></i>
</button>
```

![buttons](https://user-images.githubusercontent.com/12593751/30950696-d23a001a-a41e-11e7-84e0-d9086dbde40a.png)

Best regards,
Arek

**Comment by Justineo** [comment]
Because icons are SVG elements (like an `<img>`) in Vue-Awesome rather than characters, there are definitely some difference with icon fonts like FontAwesome. You may have to adjust styles by yourself. Maybe try something like:

```css
.fa-icon {
  vertical-align: middle;
}
```

**Comment by alexiej** [comment]
Thank's,

Now it's working like a charm.

![image](https://user-images.githubusercontent.com/12593751/30954010-c2f5ecf8-a42e-11e7-93a8-fa91bb2c4af3.png)

**Comment by Jacksoor** [comment]
I had the same issue with `bootstrap 4.3.1` but `vertical-align: middle` was already applied. Switching from `@fortawesome/fontawesome-svg-core`, using their css worked for me:
```css
.fa-icon {
	height: 1em;
	vertical-align: -0.125em;
}```

**Comment by Justineo** [comment]
Or you can apply flex layout on the parent element:

```css
.btn {
  display: inline-flex;
  align-items: center;
}
```
