### ISSUE TITLE
How to use Vue-awesome in Vue TypeScript template?

### ISSUE THREAD

**Issue by koddr** [Justineo/vue-awesome#64]
Hello. Thanks for awesome work!

But I have a question: how to use Vue-awesome in Vue TypeScript template (https://github.com/ducksoupdev/vue-webpack-typescript)?

Would be nice to added small integration words about TypeScript in the documentation :)

**Comment by d1820** [comment]
the readme for the project has been updated with instructions on how to get Vue awesome to work with webpack which then transpiles down with typescript using a TS loader. other than that it's just using your regular import exports of es6 to pull in the icon component and icons

**Comment by Justineo** [comment]
Configuring TS loader should be similar to configuring `babel-loader`. I'm closing this for now. If the updated README doesn't solve the problem, feel free to reopen.

**Comment by onurusluca** [comment]
Would love to see it is explained simply in documents. Couldn't get it to work with TS.
