### ISSUE TITLE
SVG Gradients

### ISSUE THREAD

**Issue by duckness** [Justineo/vue-awesome#70]
SVG Gradients are defined via a unique id in the SVG, using multiples of the same SVG with the same gradient creates problems because now you are defining the unique id multiple times. 

I have made a [jsfiddle](http://jsfiddle.net/qojhct4x/1/) to demonstrate, as well as a workaround/fix. The browser I used is Chrome, and the problem is reproducible on Firefox as well. This doesn't occur on Edge/Safari (but it's probably undefined behavior anyway).

**Comment by Justineo** [comment]
Fixed this in `v2.3.4`. Now `id`s or `xml:id`s and their references (`#foo` or `xpointer(id('foo'))`) will be rewrite into unique ones when using `raw` SVG string.
