### ISSUE TITLE
Cannot load font in production mode.

### ISSUE THREAD

**Issue by gezichenshan** [Justineo/vue-awesome#72]
wrong link: file:///Users/user/ryanown/khlt/registration/dist/static/css/static/fonts/fontawesome-webfont.af7ae50.woff2

the right should be file:///Users/user/ryanown/khlt/registration/dist/static/fonts/fontawesome-webfont.af7ae50.woff2

I see in the css bundle 
```
*/@font-face{
font-family:FontAwesome;
src:url(static/fonts/fontawesome-webfont.674f50d.eot);
src:url(static/fonts/fontawesome-webfont.674f50d.eot?#iefix&v=4.7.0)
format("embedded-opentype"),url(static/fonts/fontawesome-webfont.af7ae50.woff2) format("woff2"),url(static/fonts/fontawesome-webfont.fee66e7.woff) format("woff"),url(static/fonts/fontawesome-webfont.b06871f.ttf) format("truetype"),url(static/img/fontawesome-webfont.912ec66.svg#fontawesomeregular)
```
I think it is the absolute url make things wrong.

**Comment by Justineo** [comment]
This project has nothing to do with icon fonts. It uses inline SVG to render icons.

Please DO read README.

**Comment by gezichenshan** [comment]
mmm...solved with issue: https://github.com/vuejs-templates/webpack/issues/166. It is not the problem by vue-awesome.
