### ISSUE TITLE
 vue-awesome integration issue

### ISSUE THREAD

**Issue by rahulkumar-aws** [Justineo/vue-awesome#75]
I am getting following error after adding vue-awesome in project
`
[Vue warn]: Unknown custom element: <icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Please check this issue.

**Comment by Justineo** [comment]
You are not providing any useful information (like how you are registering your component). Please read the [README](https://github.com/Justineo/vue-awesome#es-modules-with-npm--vue-loader-recommended) and follow the instructions.
