### ISSUE TITLE
How to add an event listener for an icon?

### ISSUE THREAD

**Issue by barikedoo** [Justineo/vue-awesome#76]
Hi! I'm trying to add an event listener for an <icon> component like this:

<icon name="times" class="single-item-details__close" @click="closeItem"></icon>

But apparently it does not work, cause after the build compiles you actually click on the svg, which does not have an event listener. 

Don't really want to add it using vanilla js, like document.querySelector....

What is the better way?

**Comment by Justineo** [comment]
[Binding Native Events to Components](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components)
