### ISSUE TITLE
include/support font-awesome 5

### ISSUE THREAD

**Issue by yehosef** [Justineo/vue-awesome#78]
just released - more icons
https://fontawesome.com/

**Comment by Justineo** [comment]
I think I'll add FA5 icons in `v3.0.0` and  will continue to maintain both `2.x` & `3.x`.

**Comment by Los** [comment]
I'm waiting for it too. The Discord icon is a must have.
Would love to see the v3! <3

**Comment by grimaldou** [comment]
Do you know if I update the package.json with the new version all the new icons can be updated?

**Comment by okandas** [comment]
hello there, any chance we can help with the upgrade to font-awesome 5

**Comment by okandas** [comment]
@justineo I am in agreement, simplicity first. will stick to the one you kindly gifted and wait until a cleaner and simpler solution for the upgrade

**Comment by vinceok** [comment]
waiting for 5 , thanks

**Comment by Justineo** [comment]
Sorry for the delay folks, I just published `vue-awesome@3.0.0` with all free icons in FA5. Instructions are also updated in the [README](https://github.com/Justineo/vue-awesome#usage).
