### ISSUE TITLE
is there a way to optimize the rendering/loading of the svgs ?

### ISSUE THREAD

**Issue by ctf0** [Justineo/vue-awesome#79]
atm am using the lib with a package am building https://github.com/ctf0/Laravel-Media-Manager which have to load a minimum of 20 items at any given time.

so for example if you are viewing like a 50 items at the same time, we now have at least 70 svg that needs to be rendered.

so i was asking, is there **ANYWAY** to optimize the loading of the svg ?

**Comment by Justineo** [comment]
I don't quite understand what you mean by saying “optimize” yet. The icons can be hand picked and only those you choose to render will be bundled with the app's JavaScript code. The only redundancy is that if you render the app on server side, the same icon may appear many times in the same page (also it's not a big deal with gzip). So can you elaborate on in what way do you want to optimize the current situation?

**Comment by ctf0** [comment]
this part
> The only redundancy is that if you render the app on server side, the same icon may appear many times in the same page

but i after more researching i see there isnt much could be done from the lib side.

the final result is chrome is dumb when it comes to svg, so its more of a problem with the browser more than the svg it self.

thanx & sorry for the inconvenience.

**Comment by Justineo** [comment]
F.Y.I. GitHub itself is using inline SVG everywhere from a Ruby backend.

**Comment by ctf0** [comment]
yeah yeah i know, the reason i converted from the fw font to svg i thought it would be much faster specially that we only load what we need, but what happened is that chrome has made it even worse.
