### ISSUE TITLE
vue-cli tests

### ISSUE THREAD

**Issue by dcrystalj** [Justineo/vue-awesome#80]
Using vue-cli I can successfully run npm dev but I get error when I am running tests. I get
```
   ...\widgets\node_modules\vue-awesome\icons\volume-up.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Icon from '../components/Icon.vue'
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import
```

**Comment by Justineo** [comment]
Thanks for reporting!

I've put this in [README](https://github.com/Justineo/vue-awesome#unit-testing-with-jest) now:

> Make sure to whitelist vue-awesome from the transformIgnorePattern. Add following configuation in test/unit/jest.conf.js:
>
> ```diff
> + transformIgnorePatterns: [
> +   '/node_modules(?![\\\\/]vue-awesome[\\\\/])/'
> + ],
> ```
>
> *Don't import all icons if you don't want to make unit testing slow because this will transform all icons from ES module and thus slow down the test process.*
