### ISSUE TITLE
Screen Reader Support

### ISSUE THREAD

**Issue by dev1337** [Justineo/vue-awesome#86]
It would be nice if there was some kind of `srText` parameter that would allow us to set some text equivalent of the icon for screen readers only, just like how FA does this with the `sr-only` class and by adding `aria-hidden="true"` to the svg.

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/34902028-2cb2bfd6-f84e-11e7-8dcf-abd67f6352ae.png)

Will `label` prop work in your case?

**Comment by dev1337** [comment]
Oh yes, this is perfect. Seems like I overlooked this.
