### ISSUE TITLE
High CPU usage when "spin" is used

### ISSUE THREAD

**Issue by soichih** [Justineo/vue-awesome#90]
I just realized that, when I set "spin" attribute on my icon, the CPU usage on Chrome goes way up.

```
<icon name="cog"/>
```
![nospin](https://user-images.githubusercontent.com/923896/36041333-2cbeca76-0d96-11e8-89a0-d3d10e0424a4.png)

```
<con name="cog" spin/>
```
![spin](https://user-images.githubusercontent.com/923896/36041351-38255a1a-0d96-11e8-9f43-50fff13cd050.png)

I have about dozen icons on my page, but only 1 is set with "spin" in this case. I am running Ubuntu 16 Gnome3 on XPS 15 (GTX 1050 GPU). Is this expected?

**Comment by Justineo** [comment]
> Ubuntu 16 Gnome3 on XPS 15 (GTX 1050 GPU)

It's weird...I can't test this under Ubuntu ATM. I haven't come across this issue yet. But I believe this repo did nothing except adding a CSS animation for a infinite spin.

**Comment by soichih** [comment]
I forgot to mention that this is happening on Chrome 60.0. I haven't tried other browsers yet, but it could be a bug/issue with Chrome..

**Comment by Justineo** [comment]
> Chrome specific issue

Maybe Chrome on Ubuntu...

**Comment by Justineo** [comment]
I'm afraid that there's not much I can do about this so I'll close this for now.
