### ISSUE TITLE
pulse prop is spinning the icon instead of pulsating 

### ISSUE THREAD

**Issue by Sparkenstein** [Justineo/vue-awesome#91]
I followed the official tutorial to include the vue-awesome in my web app. I was trying to pulsate one icon so I set the Boolean pulse to true, and instead of making the icon pulse, it started spinning in cloackwise direction.  Here is my code:
`<icon pulse name="500px" scale="3"></icon>` 
I am using vue-awesome ^2.3.4 with buefy ^0.6.3
I verified this behavior with other icons life flag, download too. they all spin instead of pulse. The only difference between spin and pulse I observed is, spin is more smooth and pulse is a little rough animation.

**Comment by Justineo** [comment]
That's the expected behavior IMO because FontAwesome's pulse is a step animation of spinning.
