### ISSUE TITLE
vue-awesome picker

### ISSUE THREAD

**Issue by enghelewa** [Justineo/vue-awesome#93]
I am trying to make a vue component which is an icon picker that will use this plugin. But I don't know how to show all of the available icons using your component.
Any help will be appreciated :)

**Comment by Justineo** [comment]
https://github.com/Justineo/vue-awesome/blob/master/README.md#usage

You can use any available FontAwesome 4 icon names (without prefix).

**Comment by enghelewa** [comment]
That's right I used wrong icon names.
