### ISSUE TITLE
Is there a way to get fa-inverse?

### ISSUE THREAD

**Issue by leto** [Justineo/vue-awesome#97]
Is there a way to get inverted icons in FA5? Adding a class of `fa-inverse` does not seem to work on 3.0.0

Thanks

**Comment by Justineo** [comment]
You don't need to use `fa-inverse`. Just set color for the icon in CSS and it will just work:

```html
<icon style="color: #fff" name="..."/>
```

**Comment by leto** [comment]
Thanks for your quick response, in case you like to know, I am using vue-awesome in https://github.com/MyHush/hush-ng and it's great, thanks! 
![hush-cmc-prices-eur](https://user-images.githubusercontent.com/30298/39060487-5667c564-4476-11e8-8b80-9d30b333cac0.png)
