### ISSUE TITLE
Changelog and releases outdated

### ISSUE THREAD

**Issue by dsbert** [Justineo/vue-awesome#98]
NPM reports the latest version is `3.0.0`. However, the change log only shows up to `2.3.5` and the release page only contains a single release for `v2.0`

**Comment by chanlito** [comment]
It'd be nice to see changes from v2 to v3.

**Comment by Justineo** [comment]
All free icons in Font Awesome 5 are ported to `vue-awesome@3.0.0`. (I just updated the changelog.)

**Comment by Justineo** [comment]
Changelog has been up-to-date for recent versions.
